#ifndef EMP_AGMPC_H__
#define EMP_AGMPC_H__
#include "emp-agmpc/abitmp.h"
#include "emp-agmpc/cmpc_config.h"
#include "emp-agmpc/fpremp.h"
#include "emp-agmpc/helper.h"
#include "emp-agmpc/mpc.h"
#include "emp-agmpc/netmp.h"
#endif// EMP_AGMPC_H__
